export const rows = [
    { id: 1, name: 'John Doe', email: 'John@gmail.com', age: '25', phone: '1234567890', access: 'Admin' },
    { id: 2, name: 'Jane Smith', email: 'Jane@email.com', age: '30', phone: '0987654321', access: 'User' },
    { id: 3, name: 'Mike Brown', email: 'mike@email.com', age: '42', phone: '9876543210', access: 'Manager' },
    { id: 4, name: 'Emily Johnson', email: 'emily@example.com', age: '35', phone: '5555555555', access: 'User' },
    { id: 5, name: 'Michael Lee', email: 'michael@example.com', age: '28', phone: '6666666666', access: 'Admin' },
    { id: 6, name: 'Sarah Miller', email: 'sarah@example.com', age: '38', phone: '7777777777', access: 'User' },
    { id: 7, name: 'David Wilson', email: 'david@example.com', age: '45', phone: '8888888888', access: 'Admin' },
    { id: 8, name: 'Emma Davis', email: 'emma@example.com', age: '29', phone: '9999999999', access: 'User' },
    { id: 9, name: 'James Taylor', email: 'james@example.com', age: '33', phone: '1010101010', access: 'Manager' },
    { id: 10, name: 'Olivia Martinez', email: 'olivia@example.com', age: '37', phone: '1212121212', access: 'User' },
    { id: 11, name: 'William Anderson', email: 'william@example.com', age: '40', phone: '1313131313', access: 'Admin' },
    { id: 12, name: 'Ava Thomas', email: 'ava@example.com', age: '31', phone: '1414141414', access: 'User' },
    { id: 13, name: 'Benjamin Hernandez', email: 'benjamin@example.com', age: '44', phone: '1515151515', access: 'Admin' },
    { id: 14, name: 'Mia Nelson', email: 'mia@example.com', age: '27', phone: '1616161616', access: 'User' },
    { id: 15, name: 'Ethan White', email: 'ethan@example.com', age: '39', phone: '1717171717', access: 'Manager' },
    { id: 16, name: 'Sophia Gonzalez', email: 'sophia@example.com', age: '32', phone: '1818181818', access: 'User' },
    { id: 17, name: 'Alexander Carter', email: 'alexander@example.com', age: '36', phone: '1919191919', access: 'Admin' },
    { id: 18, name: 'Chloe Perez', email: 'chloe@example.com', age: '41', phone: '2020202020', access: 'User' },
    { id: 19, name: 'Daniel Roberts', email: 'daniel@example.com', age: '34', phone: '2121212121', access: 'Admin' },
    { id: 20, name: 'Isabella Ramirez', email: 'isabella@example.com', age: '29', phone: '2222222222', access: 'User' },
    { id: 21, name: 'Joseph Evans', email: 'joseph@example.com', age: '43', phone: '2323232323', access: 'Manager' },
    { id: 22, name: 'Charlotte Russell', email: 'charlotte@example.com', age: '30', phone: '2424242424', access: 'User' },
    { id: 23, name: 'Samuel King', email: 'samuel@example.com', age: '38', phone: '2525252525', access: 'Admin' },
    { id: 24, name: 'Avery Foster', email: 'avery@example.com', age: '35', phone: '2626262626', access: 'User' },
    { id: 25, name: 'Victoria Diaz', email: 'victoria@example.com', age: '40', phone: '2727272727', access: 'Manager' },
    { id: 26, name: 'Henry Barnes', email: 'henry@example.com', age: '37', phone: '2828282828', access: 'User' },
    { id: 27, name: 'Grace Powell', email: 'grace@example.com', age: '33', phone: '2929292929', access: 'Admin' },
    { id: 28, name: 'Charles Ward', email: 'charles@example.com', age: '42', phone: '3030303030', access: 'User' },
    { id: 29, name: 'Lillian Torres', email: 'lillian@example.com', age: '31', phone: '3131313131', access: 'Admin' },
];
  
export const columns = [
    { field: 'id', headerName: 'ID', flex: 1, align: 'center', headerAlign: 'center', type: 'number' },
    { field: 'name', headerName: 'Name', flex: 1, align: 'center', headerAlign: 'center', type: 'string' },
    { field: 'email', headerName: 'Email', flex: 1, align: 'center', headerAlign: 'center', type: 'string'},
    { field: 'age', headerName: 'Age', flex: 1, align: 'center', headerAlign: 'center', type: 'number'},
    { field: 'phone', headerName: 'Phone', flex: 1, align: 'center', headerAlign: 'center', type: 'string'},
    {field: 'access', headerName: 'Access', flex: 1, align: 'center', headerAlign: 'center', type: 'string'}
    ];